# .github/workflows/ios-build.yml

name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS app on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # or whatever version you're using

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS app
        run: |
          flutter build ios --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
