name: lutfan
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.3
  easy_localization: ^3.0.2
  image_picker: ^1.0.2
  url_launcher: ^6.1.14

  # UI
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_styled_toast: ^2.1.3
  concentric_transition: ^1.0.3
  # carousel_slider: ^4.2.1
  flutter_carousel_widget: ^3.1.0

  #NERWORK
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  path: ^1.8.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^7.6.0

  #DB
  shared_preferences: ^2.5.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.10.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/lesson/
    - assets/svg/icon/
    - assets/svg/product/
    - assets/images/